"""Added address

Revision ID: 21a583a6279c
Revises: d97864dc7433
Create Date: 2026-04-22 15:47:39.800474

"""

from typing import Sequence, Union
from sqlmodel import SQLModel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21a583a6279c"
down_revision: Union[str, Sequence[str], None] = "d97864dc7433"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seller", sa.Column("address", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller", "address")
    # ### end Alembic commands ###
