"""added delivery partner

Revision ID: 50ab784092ae
Revises: 21a583a6279c
Create Date: 2026-04-22 22:35:06.457380

"""

from typing import Sequence, Union
from sqlmodel import SQLModel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "50ab784092ae"
down_revision: Union[str, Sequence[str], None] = "21a583a6279c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("serviceable_zip_codes", sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "seller", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.alter_column(
        "seller",
        "password_hash",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.drop_column("seller", "address")
    op.add_column(
        "shipment", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "shipment", sa.Column("delivery_partner_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "shipment", "delivery_partner", ["delivery_partner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shipment", type_="foreignkey")
    op.drop_column("shipment", "delivery_partner_id")
    op.drop_column("shipment", "created_at")
    op.add_column(
        "seller", sa.Column("address", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "seller",
        "password_hash",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.drop_column("seller", "created_at")
    op.drop_table("delivery_partner")
    # ### end Alembic commands ###
